export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const GET_RECIPE = 'GET_RECIPE';
export const ADD_SHOPPINGLIST = 'ADD_SHOPPINGLIST';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const LIKED_RECIPES = 'LIKED_RECIPES';
